#端口
server:
  port: 8082
#数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/dcy?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: "0325"
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: account-Server

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
