spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/hyb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: "0325"


mybatis:
  type-aliases-package: com.springboot.pojo
  mapper-locations: mappers/*.xml


#jdbc.driverClassName=com.mysql.jdbc.Driver
#jdbc.url=jdbc:mysql://172.27.101.186:3306/leyou
#jdbc.username=root
#jdbc.password=0325