server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/dcy?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: "0325"

mybatis:
  type-aliases-package: com.springboot.pojo
  mapper-locations: mappers/*.xml

# 读取yml配置信息
userinfo:
  user-id: 1
  user-name: dcy
  blog-url: baidu.com
  hobbys: -[篮球,足球,羽毛球,乒乓球,游泳]
  blog-remark: 您好