server:
  port: 8081

dubbo:
  application:
    name: dubbodemo_provider
  registry:
    address: zookeeper://192.168.61.132
    port: 2181
  consumer:
    check: false
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.dcy.dubbo.provider.service.impl